name: Action Integration Tests

on: [push]

jobs:
  version-pinned:
    strategy:
      matrix:
        include:
          - version-spec: '2.0.0'
            test-match-string: '2.0.0'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Do it
        id: ours
        uses: ./
        with:
          version: 2.0.0

      - name: Validate Poetry version
        run: |
          poetry --version
          [ '${{ steps.ours.outputs.version }}' == '2.0.0' ]

  latest-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Do it
        id: ours
        uses: ./

      - name: Validate Poetry installed
        run: |
          which poetry
          poetry --version

